# query_config.yaml
# 用于定义查询渠道信息时的筛选条件和显示字段

# 筛选条件 (filters)
# 如果 filters 部分不存在或为空，将不进行任何筛选，返回所有渠道。
filters:
  # 匹配模式 (match_mode)
  # "any": (默认) 满足任意一个筛选条件的渠道即被匹配。
  # "all": 必须满足所有筛选条件的渠道才被匹配。
  match_mode: "any"

  # 渠道名称筛选 (name_filters)
  # 列表中的每个字符串都会被用作正则表达式来匹配渠道名称。
  # 示例: ["Google", ".*Azure.*"]
  name_filters: []

  # 渠道分组筛选 (group_filters)
  # 匹配属于列表中任何一个分组的渠道。
  # 示例: ["default", "vip"]
  group_filters: []

  # 模型筛选 (model_filters)
  # 匹配模型列表中包含任意一个指定模型的渠道。
  # 示例: ["gpt-4", "claude-2"]
  model_filters: []

  # 标签筛选 (tag_filters)
  # 匹配包含列表中任何一个标签的渠道。
  # 示例: ["stable", "backup"]
  tag_filters: []

  # 渠道类型筛选 (type_filters)
  # 匹配类型 ID 在列表中的渠道。
  # 示例: [1, 3, 5]
  type_filters: []

# 显示字段 (query_fields)
# 定义查询结果中要显示的渠道字段。
# 如果此列表不存在或为空，将使用默认值: ['id', 'name']
# 可用字段基本对应 One API 渠道模型的所有字段，例如:
# 'id', 'type', 'name', 'group', 'status', 'priority', 'weight', 'models', 'created_time'
query_fields:
  - "name"
  - "group"